name: Simple Node CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Code 
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Node setup 
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # 3. Dependencies install  (if package.json exists)
      - name: Install dependencies
        run: |
          if [ -f package.json ]; then npm install; fi

      # 4. Run your Node program
      - name: Run main file
        run: |
          if [ -f index.js ]; then node index.js; else echo "No entry file found"; fi
